apiVersion: batch/v1
kind: Job
metadata:
    name: sandy-terraform-rds
    namespace: microservices
spec:
    template:
        metadata:
            namespace: microservices
        spec:
            containers:
                -   name: sandy-terraform-rds
                    image: 702037529261.dkr.ecr.us-west-2.amazonaws.com/sandy-microservice-terraform
                    env:
                    -   name: AWS_ACCESS_KEY_ID
                        valueFrom:
                            secretKeyRef:
                                name: aws-terraform-cred
                                key: AWS_ACCESS_KEY_ID
                    -   name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                            secretKeyRef:
                                name: aws-terraform-cred
                                key: AWS_SECRET_ACCESS_KEY
                    -   name: TF_VAR_team_name
                        value: sandy
                    args:
                      - plan
            restartPolicy: Never
    backoffLimit: 4
